# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-02 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pkey', models.IntegerField(max_length=10)),
                ('date', models.IntegerField(max_length=10)),
                ('invoice_number', models.IntegerField(max_length=10)),
                ('total_quantity', models.IntegerField(max_length=10)),
                ('total_amount', models.IntegerField(max_length=10)),
                ('total_tax', models.IntegerField(max_length=10)),
            ],
        ),
    ]
